# Generated by Django 6.0.4 on 2026-04-29 00:15

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Endereço de e-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('fone', models.CharField(help_text='Número de telefone', max_length=15, verbose_name='Telefone')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='usuarios', variations={}, verbose_name='Foto')),
                ('plano', models.CharField(help_text='Plano do aluno', max_length=100, verbose_name='Plano')),
                ('validadePlano', models.DateField(help_text='Data do término do plano', verbose_name='Validade plano')),
                ('endereco', models.CharField(help_text='Endereço completo', max_length=100, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
