# Generated by Django 6.0.4 on 2026-04-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numero do armario', max_length=5, unique=True, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Armário',
                'verbose_name_plural': 'Armários',
            },
        ),
    ]
