# Generated by Django 6.0.4 on 2026-05-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do sala', max_length=100, unique=True, verbose_name='Nome')),
                ('tipo', models.CharField(help_text='Tipo da sala', max_length=100, verbose_name='Tipo')),
                ('descricao', models.TextField(help_text='Descrição e observações sobre a sala', max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
