# Generated by Django 6.0.4 on 2026-04-30 23:09

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Endereço de e-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('fone', models.CharField(help_text='Número de telefone', max_length=15, verbose_name='Telefone')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='usuarios', variations={}, verbose_name='Foto')),
                ('especialidade', models.CharField(help_text='Especialidade do Instrutor', max_length=150, verbose_name='Especialidade')),
                ('dataAdmissao', models.DateField(help_text='Data de admissão do Instrutor', verbose_name='Admissão')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
            },
        ),
    ]
